#pragma once
#include <unordered_map>
#include <vector>
#include <string>
#include <optional>
#include <cassert>
#include <cstdio>
#include <cmath>
#include <queue>
#include <bitset>
#include <memory>
#include <algorithm>
#include <fstream>
#include "json.hpp"
#include "entt/entt.hpp"
#include "entt/resource/fwd.hpp"
#include "entt/core/hashed_string.hpp"
#include "SFML/Graphics.hpp"